### ISSUE TITLE
Running behind reverse proxy for example traefik

### ISSUE THREAD

**Issue by denis-ev** [iay/shibboleth-idp-docker#12]
Is it possible to disable the SSL and just connect to the service via http?
I'd like to run it behind traefik and it's just easier not to have ssl enabled by the service.

For running I'd recommend docker-compose instead of a run script or both.

**Comment by iay** [comment]
> Is it possible to disable the SSL and just connect to the service via http?
>
> I'd like to run it behind traefik and it's just easier not to have ssl enabled by the service.

There are two TLS-protected ports needed if you want to support all the profiles. The front-channel (browser-facing one) is easy to switch to HTTP if you want to run behind a reverse proxy of some kind.

You'd need to tweak the configuration a bit to do that. I haven't, but off the top of my head you'd need to expose port 80 in the Dockerfile and you might need to enable Jetty's http module (I can't remember if it's enabled by default). You could probably do that with a local overlay, though.

The back channel (used for asynchronous requests from SPs for things like SAML 1.1 Attribute Query and Enhanced Client / Proxy requests) really can't be easily intermediated because the IdP needs to see the client certificate so that it can provide the appropriate trust semantics. If you don't have any of those use cases (and most people these days do not) then just ignore this and simply not publish port 8080. Of course you need to not have anything in your metadata that says you use that port.

I'd be happy to take a PR if you found a way of doing this that was essentially optional. You might, for example, end up with another `jetty-base-`_XXXX_. I'd probably be OK with re-adding the `EXPOSE 80` I removed a few months back, on the basis that there's no real harm in it.
 
> For running I'd recommend docker-compose instead of a run script or both.

The original reason I didn't use `docker compose` is that it was still being developed when I started this project, and I already had everything working by the time it became stable ;-)

These days, there are (mainly multi-container) projects where I do use `docker compose` but I probably won't use it for this one as most of the newer container engines (RH's `podman`, VMware's new `vctl` thing) don't support it at all. They mostly support vanilla `docker` commands, though. My current plan is to move my own installation to `podman` as I run mainly CentOS machines and Red Hat have more recently set their face against supporting Docker in, for example, RHEL 8. That seems to be mostly a question of saying `alias docker=podman`.

I used to have a directory for alternate service management scripts but they got enough out of date that I deleted it. Again, though, if you were to provide me a PR for a `docker-compose` file in a `contrib/` directory I'd probably accept that as it might be useful to someone else.

I'll leave this issue open for now in case you want to follow up.
