### ISSUE TITLE
./run and ./test: failed to create endpoint shibboleth-idp on network bridge

### ISSUE THREAD

**Issue by arne-cl** [iay/shibboleth-idp-docker#3]
When i try to run `./run` or `./test`, this error occurs:

``` bash
 ~/repos/shibboleth-idp-docker $ ./test
43f7e3200b067237d3e1eb6fa337410b8592dfbb1a2da2795def6432bb5de90b
Error response from daemon: Cannot start container 43f7e3200b067237d3e1eb6fa337410b8592dfbb1a2da2795def6432bb5de90b: failed to create endpoint shibboleth-idp on network bridge: Error starting userland proxy: listen tcp 192.168.117.26:8443: bind: cannot assign requested address
```

**Comment by iay** [comment]
The current arrangement, with the IP address to bind embedded in scripts, is not a good one. Rather than just documenting that people should change that, I think a better solution is to have workable defaults and to allow the creation of a settings file to override those.

I'm going to close your PR and implement that approach.

Incidentally, binding to 127.0.0.1 probably isn't great for most people, as the IdP would then be visible only from the local machine. 0.0.0.0 is probably a better default, binding to all external interfaces.
